FROM 133013689155.dkr.ecr.us-east-1.amazonaws.com/php7.0-apache2:latest

# Install Supervisor.
RUN \
  apt-get update && \
  apt-get install -y supervisor cron && \
  rm -rf /var/lib/apt/lists/*

COPY . /var/www/html/

COPY docker-files/vsites-worker.json /opt/consul-template/vsites.json
#COPY docker-files/vsites.ctmpl /opt/consul-template/vsites.ctmpl
COPY docker-files/local-config.ctmpl /opt/consul-template/local-config.ctmpl
#COPY docker-files/consul.sh.ctmpl /opt/consul-template/consul.sh.ctmpl
COPY docker-files/consul-worker.sh.ctmpl /opt/consul-template/service.sh.ctmpl
#COPY docker-files/ssl_certificates_generator.sh.ctmpl /opt/consul-template/ssl_certificates_generator.sh.ctmpl


COPY docker-files/docker-php-entrypoint-worker /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-entrypoint-worker

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
COPY docker-files/cron.conf /etc/supervisor/conf.d/cron.conf
COPY docker-files/crontab.txt /tmp/crontab.txt
RUN crontab /tmp/crontab.txt

ENTRYPOINT ["docker-php-entrypoint-worker"]
